### ISSUE TITLE
Add a podspec for IP-UIKit-Wisdom to IntrepidPursuits/Specs

### ISSUE THREAD

**Issue by nservidio** [IntrepidPursuits/uikit-wisdom#8]

**Comment by loganwright** [comment]
There is already a podspec, but that's not the name of the repo.  I think the repo should be changed to a name that more people expect, let's confirm w/ @brightredchilli.

Ying, if you're ok with it, I think `intrepidPursuits/Intrepid-Wisdom` should just be `intrepidPursuits/specs`

Let me know if you're ok w/ it and I can make the change real quick.

**Comment by brightredchilli** [comment]
I thought about it but I didn't want confusion with the cocoapods specs that we are also forking. The benefits of maintaining our own is that we wouldn't need to participate and continue to merge changes into the main repo, as well as giving us the ability to keep our projects private.

Totally not against making it a public repo. Is this what you're suggesting?

**Comment by Benuuu** [comment]
Ah, didn't realize IntrepidPursuits/Intrepid-Wisdom existed.  I had been searching for Specs and couldn't find it.

It looks like it is already public.

**Comment by brightredchilli** [comment]
good point :monkey:

**Comment by loganwright** [comment]
@brightredchilli @Benuuu @nservidio 

I didn't consider the cocoapods fork conflict, do we still need it?  I know that was originally how you added podspecs to the main repository, but if we're not preserving it or maintaining it, we could probably delete it and use it just for internal.

I think our specs repo and the global cocoapods repo should absolutely be different.

If everyone likes `intrepid-wisdom`, we can just add  a note in the README so people know to add it to their source.

I think `Specs` makes more sense just because that's what people look for
